# 🐻‍❄️🏳️‍⚧️ Logrin: Modern, async-aware logging framework for C++20
# Copyright (c) 2026 Noel Towa <cutie@floofy.dev>, et al.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# TODO(@auguwu/Noel): switch to `cr.noel.pink/ci/{{compiler}}:{{version}}` once available

if_changed: &if_changed
  if_changed:
    include:
      - "**/*"
    exclude:
      - ".github/**"
      - ".vscode/**"
      - "hack/**"
      - ".ci/**"
      - "nix/**"
      - "tools/bazeldist"
      - "tools/hotpatch-release.py"
      - "CHANGELOG.md"
      - "renovate.json"
      - "flake.lock"
      - ".*ignore"
      - ".clangd"
      - ".envrc"

plugins: &plugins
  - "docker#5.13.0":
      image: "ghcr.io/noelware/violet/ci:clang-22"
      propagate-environment: true
      environment:
        - USE_BAZEL_VERSION
        - CXX
        - CC
  - "cache#1.10.0":
      manifest: "MODULE.bazel"
      path: "~/.cache/bazel"
      restore: pipeline
      save: pipeline

matrix_plugins: &matrix_plugins
  - "docker#5.13.0":
      image: "ghcr.io/noelware/violet/ci:{{matrix.compiler}}"
      propagate-environment: true
      environment:
        - USE_BAZEL_VERSION
        - CXX
        - CC
  - "cache#1.10.0":
      manifest: "MODULE.bazel"
      path: "~/.cache/bazel"
      restore: pipeline
      save: pipeline

env:
  USE_BAZEL_VERSION: "8.6.0"
steps:
  - group: ":linux: Linux / x64"
    steps:
      - label: ":bazel: Feature Configuration [exceptions={{matrix.exceptions}} rtti={{matrix.rtti}}]"
        key: "bazel-configuration"
        agents:
          queue: "linux"
        <<: *if_changed
        plugins: *plugins
        env:
          CXX: "clang++-22"
          CC: "clang-22"
        matrix:
          setup:
            exceptions:
              - "yes"
              - "no"
            rtti:
              - "yes"
              - "no"
        command: |
          flags="--config=ci --config=cxx26 --action_env=CC --action_env=CXX "
          if [ "{{matrix.exceptions}}" == "yes" ]; then
            flags+=("--cxxopt=-fexceptions --host_cxxopt=-fexceptions ")
          else
            flags+=("--cxxopt=-fno-exceptions --host_cxxopt=-fno-exceptions ")
          fi

          if [ "{{matrix.rtti}}" == "yes" ]; then
            flags+=("--cxxopt=-frtti --host_cxxopt=-frtti")
          else
            flags+=("--cxxopt=-fno-rtti --host_cxxopt=-fno-rtti")
          fi

          bazel test //... $${flags}
      - label: ":bazel: Compiler Compatibility [{{matrix.compiler}}]"
        key: "bazel-compiler-support"
        <<: if_changed
        agents:
          queue: "linux"
        plugins: *matrix_plugins
        matrix:
          - gcc-15
          - gcc-14
          - clang-22
          - clang-21
          - clang-20
        command: |
          COMPILER="{{matrix.compiler}}"
          case "{{matrix.compiler}}" in
            gcc-15|gcc-14)
              export CC=gcc
              export CXX=g++

              ;;

            clang-*)
              version="$${COMPILER##*-}"
              export CC="clang-$${version}"
              export CXX="clang++-$${version}"

              ;;
          esac

          bazel test --config=ci --config=cxx26 --action_env=CC --action_env=CXX //...
      - label: ":bazel: C++{{matrix.standard}} [{{matrix.compiler}}]"
        key: "bazel-cxx-standard"
        <<: if_changed
        agents:
          queue: "linux"
        plugins: *matrix_plugins
        matrix:
          setup:
            compiler:
              - gcc-15
              - gcc-14
              - clang-22
              - clang-21
              - clang-20
            standard:
              - "23"
              - "20"
        command: |
          COMPILER="{{matrix.compiler}}"
          case "{{matrix.compiler}}" in
            gcc-15|gcc-14)
              export CC=gcc
              export CXX=g++

              ;;

            clang-*)
              version="$${COMPILER##*-}"
              export CC="clang-$${version}"
              export CXX="clang++-$${version}"

              ;;
          esac

          bazel test --config=ci --config=cxx{{matrix.standard}} --action_env=CC --action_env=CXX //...
      - label: ":bazel::opentelemetry: OpenTelemetry Sink"
        key: "opentelemetry-sink"
        <<: *if_changed
        agents:
          queue: "linux"
        plugins: *plugins
        env:
          CXX: "clang++-22"
          CC: "clang-22"
        command: bazel build //src/sinks:opentelemetry --config=ci --//:opentelemetry=True --config=cxx26
      - label: ":microscope: AddressSanitizer / UndefinedBehaviourSanitizer"
        key: "asan-ubsan"
        <<: *if_changed
        agents:
          queue: "linux"
        plugins: *plugins
        env:
          UBSAN_SYMBOLIZER_PATH: "/usr/bin/llvm-symbolizer-22"
          ASAN_SYMBOLIZER_PATH: "/usr/bin/llvm-symbolizer-22"
          CXX: "clang++-22"
          CC: "clang-22"
        command: bazel test --//:opentelemetry=True --config=ci --config=cxx26 --config=asan --config=ubsan --action_env=CC --action_env=CXX --test_env=ASAN_SYMBOLIZER_PATH --test_env=UBSAN_SYMBOLIZER_PATH
