#!@bash@/bin/bash
# +---------------------------------------------------------------------------------+
# 🐻‍❄️🏳️‍⚧️ Logrin: Modern, async-aware logging framework for C++20
# Copyright (c) 2026 Noel Towa <cutie@floofy.dev>, et al.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# +---------------------------------------------------------------------------------+

set -euo pipefail

echo "[logrin/devshell] Preparing environment..."

# For sanitizers, we need to have Bazel include our headers since it can't *usually* find them.
CWD=$(pwd)

rg() {
    "@ripgrep@/bin/rg" $@
    return $?
}

# Check if `.usr.bazelrc` exists. If it doesn't then, we'll add our own configuration
# that should work on NixOS.
if [ ! -f "$CWD/.usr.bazelrc" ]; then
    echo "[logrin/devshell] Missing \`.usr.bazelrc\` in $CWD, adding proper configuration for NixOS"
    cat > "$CWD/.usr.bazelrc" <<EOF
# +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
# +=+     THIS FILE WAS AUTOMATICLLY GENERATED BY THE NIX SHELL ENVIRONMENT       +=+
# +=+ You are free to modify this to your heart's content. The shell environment  +=+
# +=+ will hot-replace instead of overwriting your changes. You have been warned! +=+
# +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
# This is a workaround for missing standard C++ headers on NixOS using the wrapped
# \`clang\` interface.
#
# Related: https://github.com/NixOS/nixpkgs/issues/150655
build --cxxopt=-xc++ --host_cxxopt=-xc++

# This line here is where the real header files for sanitizers will be used.
# DO NOT EDIT THIS. THE SHELL ENVIRONMENT WILL MODIFY THIS FOR NEW LLVM VERSIONS
# BEING TESTED.
build:san --copt=-I@compiler-rt@/include --host_copt=-I@compiler-rt@/include
EOF
else
    echo "[logrin/devshell] Hot-patching sanitizer includes if necessary..."

    tgt="build:san --copt=-I@compiler-rt@/include --host_copt=-I@compiler-rt@/include"
    if rg -q '^build:san' "$CWD/.usr.bazelrc"; then
        current=$(rg '^build:san' "$CWD/.usr.bazelrc")
        if [ "$current" != "$tgt" ]; then
            echo "[logrin/devshell] Detected mismatched sanitizer line! Patching..."
            echo "                current = $current"
            echo "                target  = $tgt"

            sed -i "s|^build:san.*|$tgt|" "$CWD/.usr.bazelrc"
        fi
    else
        echo "[logrin/devshell] No sanitizer line found! Adding..."
        printf "# This line here is where the real header files for sanitizers will be used.\n" >> "$CWD/.usr.bazelrc"
        printf "# DO NOT EDIT THIS. THE SHELL ENVIRONMENT WILL MODIFY THIS FOR NEW LLVM VERSIONS\n" >> "$CWD/.usr.bazelrc"
        printf "# BEING TESTED.\n" >> "$CWD/.usr.bazelrc"
        printf "%s\n" "$tgt" >> "$CWD/.usr.bazelrc"
    fi
fi
