# 🐻‍❄️🏳️‍⚧️ Logrin: Modern, async-aware logging framework for C++20
# Copyright (c) 2026 Noel Towa <cutie@floofy.dev>, et al.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: "Linux / CI"
on:
    workflow_dispatch: {}
    push:
        branches:
            - 'issues/gh-**'
            - 'feat/**'
            - master

        paths-ignore:
            - '.github/**'
            - '.vscode/**'
            - 'hack/**'
            - '.ci/**'
            - 'nix/**'

            - 'tools/bazeldist'
            - 'tools/hotpatch-release.py'

            - CHANGELOG.md
            - renovate.json
            - flake.lock
            - .*ignore
            - .clangd
            - .envrc
    pull_request:
        types: [opened, synchronize]
        branches:
            - 'issues/gh-**'
            - 'noel/**'
            - 'feat/**'
            - master
        paths:
            - '**'
permissions:
    contents: read
    checks: write
concurrency:
    group: ${{github.workflow}}-${{github.ref}}
    cancel-in-progress: true
jobs:
    bazel:
        name: "Bazel ${{matrix.bazel}} / C++${{matrix.cxx-standard}} [compiler=${{matrix.compiler}} exceptions=${{matrix.exceptions}} rtti=${{matrix.rtti}}]"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/noelware/violet/ci:${{matrix.compiler}}
        strategy:
            fail-fast: false
            matrix:
                exceptions: ["true", "false"]
                rtti: ["true", "false"]
                compiler:
                    - gcc-15
                    - gcc-14
                    - clang-22
                    - clang-21
                    - clang-20
                bazel:
                    - "7.7.1"
                    - "8.6.0"
                    # - "9.0.1"
                cxx-standard:
                    - "20"
                    - "23"
                    - "26"
                include:
                    - compiler: clang-22
                      flags: ""
                      cxx: clang++-22
                      cc: clang-22
                    - compiler: clang-21
                      flags: ""
                      cxx: clang++-21
                      cc: clang-21
                    - compiler: clang-20
                      flags: ""
                      cxx: clang++-20
                      cc: clang-20
                    - compiler: gcc-15
                      flags: ""
                      cxx: g++
                      cc: gcc
                    - compiler: clang-14
                      flags: ""
                      cxx: g++
                      cc: gcc
        env:
            BAZELFLAGS: "--config=ci --config=cxx${{matrix.cxx-standard}} --action_env=CC=${{matrix.cc}} --action_env=CXX=${{matrix.cxx}} ${{matrix.flags}}"
        steps:
            - uses: actions/checkout@v6
            - run: echo "USE_BAZEL_VERSION=${{matrix.bazel}}" >> .bazelversion
            - uses: bazel-contrib/setup-bazel@0.19.0
              with:
                bazelisk-cache: true # avoid installing Bazel each time
                repository-cache: true # cache repositories in `MODULE.bazel`
                disk-cache: ${{github.workflow}}

            - run: bazel build //... ${{env.BAZELFLAGS}}
            - run: bazel test //... ${{env.BAZELFLAGS}}

    # cmake:
    # meson:
    # asan:
    # ubsan:
